language: php
php:
  - '5.6'
  - '7.1'
  - nightly

install: composer require

script:
 - php vendor/yoya/io_avif/sample/avifdump.php -f input.avif
 - php vendor/yoya/io_avif/sample/aviftree.php -f input.avif
